### ISSUE TITLE
[Error] NeedRemoteConcent

### ISSUE THREAD

**Issue by adamPrune** [SKrotkih/YTLiveVideo-Android#4]
I'm getting an error that seems to be related to authentification.
The problem manifests itself in the following ways:
- when the app loads on my phone, a popup shows up saying "[Error] NeedRemoteConcent"
- I'm not able to see any past or current boardcasts (the same popup as the above shows up).
- the app crashes when I try to create a steam
- the following error msg is shown in the Android Studio console:
```
E/YTLiveVideo: Failed getting broadcasts list (see 'Caused by'):
    com.google.api.client.googleapis.extensions.android.gms.auth.UserRecoverableAuthIOException
        at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:297)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:880)
....
....
at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential.getToken(GoogleAccountCredential.java:267)
        at com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential$RequestHandler.intercept(GoogleAccountCredential.java:292)
```

Some context:
- in the app, I selected a google account that has the streaming functionality enabled (I can stream from my desktop PC using the YT site)
- I enabled the Youtube API v3 as it was asked in README:
https://ibb.co/FYDSS58

What could be wrong?

**Comment by medali88** [comment]
Any solution ?
